// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\analytics\libraries\{fileKey}\component\actions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/analytics/libraries/{fileKey}/component/actions?group_by={group_by}{&cursor*,end_date*,start_date*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/analytics/libraries/{fileKey}/component/actions?group_by={group_by}{&cursor*,end_date*,start_date*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of library analytics component actions data broken down by the requested dimension.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.UnauthorizedErrorResponseWithErrorBooleanResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrorBooleanResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrorBooleanResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrorBooleanResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder.ActionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder.ActionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Figma.OpenApiClient.Models.UnauthorizedErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of library analytics component actions data broken down by the requested dimension.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder.ActionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder.ActionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.Component.Actions.ActionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of library analytics component actions data broken down by the requested dimension.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Cursor indicating what page of data to fetch. Obtained from prior API call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>ISO 8601 date string (YYYY-MM-DD) of the latest week to include. Dates are rounded forward to the nearest end of a week. Defaults to the latest computed week.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end_date")]
            public string? EndDate { get; set; }
#nullable restore
#else
            [QueryParameter("end_date")]
            public string EndDate { get; set; }
#endif
            /// <summary>A dimension to group returned analytics data by.</summary>
            [QueryParameter("group_by")]
            public global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsGroupByParameter? GroupBy { get; set; }
            /// <summary>ISO 8601 date string (YYYY-MM-DD) of the earliest week to include. Dates are rounded back to the nearest start of a week. Defaults to one year prior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_date")]
            public string? StartDate { get; set; }
#nullable restore
#else
            [QueryParameter("start_date")]
            public string StartDate { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
