// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\analytics\libraries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibrariesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Figma.OpenApiClient.v1.analytics.libraries.item collection</summary>
        /// <param name="position">File key of the library to fetch analytics data for.</param>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.WithFileKeyItemRequestBuilder"/></returns>
        public global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.WithFileKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fileKey", position);
                return new global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.Item.WithFileKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.LibrariesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibrariesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/analytics/libraries", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Analytics.Libraries.LibrariesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibrariesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/analytics/libraries", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
