// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.V2.Teams.Item.Folders;
using Soenneker.Figma.OpenApiClient.V2.Teams.Item.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Figma.OpenApiClient.V2.Teams.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\teams\{teamId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTeamItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The folders property</summary>
        public global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.Folders.FoldersRequestBuilder Folders
        {
            get => new global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.WithTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeamItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/teams/{teamId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V2.Teams.Item.WithTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeamItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/teams/{teamId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
