// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Developer_logs
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\developer_logs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Developer_logsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Developer_logs.Developer_logsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Developer_logsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/developer_logs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Developer_logs.Developer_logsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Developer_logsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/developer_logs", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of developer log entries for REST API and MCP server requests made within the organization. This endpoint requires a plan access token with the `org:developer_log_read` scope.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.PostDeveloperLogsResponseResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.UnauthorizedErrorResponseWithErrorBooleanResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrorBooleanResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrorBooleanResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrorBooleanResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.PostDeveloperLogsResponseResponse?> PostAsync(global::Soenneker.Figma.OpenApiClient.Models.GetDeveloperLogsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.PostDeveloperLogsResponseResponse> PostAsync(global::Soenneker.Figma.OpenApiClient.Models.GetDeveloperLogsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Figma.OpenApiClient.Models.UnauthorizedErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.PostDeveloperLogsResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.PostDeveloperLogsResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of developer log entries for REST API and MCP server requests made within the organization. This endpoint requires a plan access token with the `org:developer_log_read` scope.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Figma.OpenApiClient.Models.GetDeveloperLogsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Figma.OpenApiClient.Models.GetDeveloperLogsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Developer_logs.Developer_logsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V1.Developer_logs.Developer_logsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V1.Developer_logs.Developer_logsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
