// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using Soenneker.Figma.OpenApiClient.V2.Webhooks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V2.Webhooks
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\webhooks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Figma.OpenApiClient.v2.webhooks.item collection</summary>
        /// <param name="position">ID of webhook to get</param>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V2.Webhooks.Item.WithWebhookItemRequestBuilder"/></returns>
        public global::Soenneker.Figma.OpenApiClient.V2.Webhooks.Item.WithWebhookItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("webhookId", position);
                return new global::Soenneker.Figma.OpenApiClient.V2.Webhooks.Item.WithWebhookItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/webhooks{?context*,context_id*,cursor*,plan_api_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/webhooks{?context*,context_id*,cursor*,plan_api_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of webhooks corresponding to the context or plan provided, if they exist. For plan, the webhooks for all contexts that you have access to will be returned, and theresponse is paginated
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetWebhooksResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetWebhooksResponseResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder.WebhooksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetWebhooksResponseResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder.WebhooksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.GetWebhooksResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.GetWebhooksResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new webhook which will call the specified endpoint when the event triggers. By default, this webhook will automatically send a PING event to the endpoint when it is created. If this behavior is not desired, you can create the webhook and set the status to PAUSED and reactivate it later.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.WebhookV2"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.WebhookV2?> PostAsync(global::Soenneker.Figma.OpenApiClient.Models.PostWebhookRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.WebhookV2> PostAsync(global::Soenneker.Figma.OpenApiClient.Models.PostWebhookRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.WebhookV2>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.WebhookV2.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of webhooks corresponding to the context or plan provided, if they exist. For plan, the webhooks for all contexts that you have access to will be returned, and theresponse is paginated
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder.WebhooksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder.WebhooksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new webhook which will call the specified endpoint when the event triggers. By default, this webhook will automatically send a PING event to the endpoint when it is created. If this behavior is not desired, you can create the webhook and set the status to PAUSED and reactivate it later.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Figma.OpenApiClient.Models.PostWebhookRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Figma.OpenApiClient.Models.PostWebhookRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V2.Webhooks.WebhooksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of webhooks corresponding to the context or plan provided, if they exist. For plan, the webhooks for all contexts that you have access to will be returned, and theresponse is paginated
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WebhooksRequestBuilderGetQueryParameters 
        {
            /// <summary>Context to create the resource on. Should be &quot;team&quot;, &quot;project&quot;, or &quot;file&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("context")]
            public string? Context { get; set; }
#nullable restore
#else
            [QueryParameter("context")]
            public string Context { get; set; }
#endif
            /// <summary>The id of the context that you want to get attached webhooks for. If you&apos;re using context_id, you cannot use plan_api_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("context_id")]
            public string? ContextId { get; set; }
#nullable restore
#else
            [QueryParameter("context_id")]
            public string ContextId { get; set; }
#endif
            /// <summary>If you&apos;re using plan_api_id, this is the cursor to use for pagination. If you&apos;re using context or context_id, this parameter is ignored. Provide the next_page or prev_page value from the previous response to get the next or previous page of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>The id of your plan. Use this to get all webhooks for all contexts you have access to. If you&apos;re using plan_api_id, you cannot use context or context_id. When you use plan_api_id, the response is paginated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("plan_api_id")]
            public string? PlanApiId { get; set; }
#nullable restore
#else
            [QueryParameter("plan_api_id")]
            public string PlanApiId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
