// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Files.Item.Images
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\files\{fileKey}\images
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/{fileKey}/images", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/{fileKey}/images", rawUrl)
        {
        }
        /// <summary>
        /// Returns download links for all images present in image fills in a document. Image fills are how Figma represents any user supplied images. When you drag an image into Figma, we create a rectangle with a single fill that represents the image, and the user is able to transform the rectangle (and properties on the fill) as they wish.This endpoint returns a mapping from image references to the URLs at which the images may be download. Image URLs will expire after no more than 14 days. Image references are located in the output of the GET files endpoint under the `imageRef` attribute in a `Paint`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetImageFillsResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrMessageResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetImageFillsResponseResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetImageFillsResponseResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.GetImageFillsResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.GetImageFillsResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns download links for all images present in image fills in a document. Image fills are how Figma represents any user supplied images. When you drag an image into Figma, we create a rectangle with a single fill that represents the image, and the user is able to transform the rectangle (and properties on the fill) as they wish.This endpoint returns a mapping from image references to the URLs at which the images may be download. Image URLs will expire after no more than 14 days. Image references are located in the output of the GET files endpoint under the `imageRef` attribute in a `Paint`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
