// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Oembed
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\oembed
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OembedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OembedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/oembed?url={url}{&maxheight*,maxwidth*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OembedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/oembed?url={url}{&maxheight*,maxwidth*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns oEmbed data for a Figma file or published Make site URL, following the [oEmbed specification](https://oembed.com/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetOEmbedResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.NotImplementedErrorResponseWithErrMessageResponse">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetOEmbedResponseResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder.OembedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetOEmbedResponseResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder.OembedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrorBooleanResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Figma.OpenApiClient.Models.NotImplementedErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.GetOEmbedResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.GetOEmbedResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns oEmbed data for a Figma file or published Make site URL, following the [oEmbed specification](https://oembed.com/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder.OembedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder.OembedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V1.Oembed.OembedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns oEmbed data for a Figma file or published Make site URL, following the [oEmbed specification](https://oembed.com/).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OembedRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum height of the embed in pixels. Defaults to 450. The response height will be adjusted to maintain a 16:9 aspect ratio with maxwidth.</summary>
            [QueryParameter("maxheight")]
            public int? Maxheight { get; set; }
            /// <summary>Maximum width of the embed in pixels. Defaults to 800. The response width will be adjusted to maintain a 16:9 aspect ratio with maxheight.</summary>
            [QueryParameter("maxwidth")]
            public int? Maxwidth { get; set; }
            /// <summary>The URL of the Figma file or published Make site to retrieve oEmbed data for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("url")]
            public string? Url { get; set; }
#nullable restore
#else
            [QueryParameter("url")]
            public string Url { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
