// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Figma.OpenApiClient.Models;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Comments;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Component_sets;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Components;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Dev_resources;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Images;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Meta;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Nodes;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Styles;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Variables;
using Soenneker.Figma.OpenApiClient.V1.Files.Item.Versions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Figma.OpenApiClient.V1.Files.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\files\{fileKey}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFileKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comments property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The component_sets property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Component_sets.Component_setsRequestBuilder Component_sets
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Component_sets.Component_setsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The components property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Components.ComponentsRequestBuilder Components
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Components.ComponentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dev_resources property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Dev_resources.Dev_resourcesRequestBuilder Dev_resources
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Dev_resources.Dev_resourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder Images
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meta property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Meta.MetaRequestBuilder Meta
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Meta.MetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nodes property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Nodes.NodesRequestBuilder Nodes
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Nodes.NodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The styles property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Styles.StylesRequestBuilder Styles
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Styles.StylesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variables property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Variables.VariablesRequestBuilder Variables
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Variables.VariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versions property</summary>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Versions.VersionsRequestBuilder Versions
        {
            get => new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.Versions.VersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/{fileKey}{?branch_data*,depth*,geometry*,ids*,plugin_data*,version*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/{fileKey}{?branch_data*,depth*,geometry*,ids*,plugin_data*,version*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the document identified by `file_key` as a JSON object. The file key can be parsed from any Figma file url: `https://www.figma.com/file/{file_key}/{title}`.The `document` property contains a node of type `DOCUMENT`.The `components` property contains a mapping from node IDs to component metadata. This is to help you determine which components each instance comes from.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetFileResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrMessageResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetFileResponseResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder.WithFileKeyItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Figma.OpenApiClient.Models.GetFileResponseResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder.WithFileKeyItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Figma.OpenApiClient.Models.BadRequestErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Figma.OpenApiClient.Models.ForbiddenErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Figma.OpenApiClient.Models.NotFoundErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Figma.OpenApiClient.Models.TooManyRequestsErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Figma.OpenApiClient.Models.InternalServerErrorResponseWithErrMessageResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Figma.OpenApiClient.Models.GetFileResponseResponse>(requestInfo, global::Soenneker.Figma.OpenApiClient.Models.GetFileResponseResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the document identified by `file_key` as a JSON object. The file key can be parsed from any Figma file url: `https://www.figma.com/file/{file_key}/{title}`.The `document` property contains a node of type `DOCUMENT`.The `components` property contains a mapping from node IDs to component metadata. This is to help you determine which components each instance comes from.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder.WithFileKeyItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder.WithFileKeyItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Figma.OpenApiClient.V1.Files.Item.WithFileKeyItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the document identified by `file_key` as a JSON object. The file key can be parsed from any Figma file url: `https://www.figma.com/file/{file_key}/{title}`.The `document` property contains a node of type `DOCUMENT`.The `components` property contains a mapping from node IDs to component metadata. This is to help you determine which components each instance comes from.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFileKeyItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Returns branch metadata for the requested file. If the file is a branch, the main file&apos;s key will be included in the returned response. If the file has branches, their metadata will be included in the returned response. Default: false.</summary>
            [QueryParameter("branch_data")]
            public bool? BranchData { get; set; }
            /// <summary>Positive integer representing how deep into the document tree to traverse. For example, setting this to 1 returns only Pages, setting it to 2 returns Pages and all top level objects on each page. Not setting this parameter returns all nodes.</summary>
            [QueryParameter("depth")]
            public double? Depth { get; set; }
            /// <summary>Set to &quot;paths&quot; to export vector data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("geometry")]
            public string? Geometry { get; set; }
#nullable restore
#else
            [QueryParameter("geometry")]
            public string Geometry { get; set; }
#endif
            /// <summary>Comma separated list of nodes that you care about in the document. If specified, only a subset of the document will be returned corresponding to the nodes listed, their children, and everything between the root node and the listed nodes.Note: There may be other nodes included in the returned JSON that are outside the ancestor chains of the desired nodes. The response may also include dependencies of anything in the nodes&apos; subtrees. For example, if a node subtree contains an instance of a local component that lives elsewhere in that file, that component and its ancestor chain will also be included.For historical reasons, top-level canvas nodes are always returned, regardless of whether they are listed in the `ids` parameter. This quirk may be removed in a future version of the API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
            /// <summary>A comma separated list of plugin IDs and/or the string &quot;shared&quot;. Any data present in the document written by those plugins will be included in the result in the `pluginData` and `sharedPluginData` properties.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("plugin_data")]
            public string? PluginData { get; set; }
#nullable restore
#else
            [QueryParameter("plugin_data")]
            public string PluginData { get; set; }
#endif
            /// <summary>A specific version ID to get. Omitting this will get the current version of the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("version")]
            public string? Version { get; set; }
#nullable restore
#else
            [QueryParameter("version")]
            public string Version { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
