// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionOneOf1Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BACK")]
        #pragma warning disable CS1591
        Back,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSE")]
        #pragma warning disable CS1591
        Close,
        #pragma warning restore CS1591
    }
}
