// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityLogEntity : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity? ActivityLogFileEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity ActivityLogFileEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity? ActivityLogFileRepoEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity ActivityLogFileRepoEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity? ActivityLogOrgEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity ActivityLogOrgEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity? ActivityLogPluginEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity ActivityLogPluginEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity? ActivityLogProjectEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity ActivityLogProjectEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity? ActivityLogTeamEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity ActivityLogTeamEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity? ActivityLogUserEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity ActivityLogUserEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity? ActivityLogWidgetEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity ActivityLogWidgetEntity { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity? ActivityLogWorkspaceEntity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity ActivityLogWorkspaceEntity { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.ActivityLogEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.ActivityLogEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogEntity();
            if("ActivityLogFileEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogFileEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity();
            }
            else if("ActivityLogFileRepoEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogFileRepoEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity();
            }
            else if("ActivityLogOrgEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogOrgEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity();
            }
            else if("ActivityLogPluginEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogPluginEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity();
            }
            else if("ActivityLogProjectEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogProjectEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity();
            }
            else if("ActivityLogTeamEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogTeamEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity();
            }
            else if("ActivityLogUserEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogUserEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity();
            }
            else if("ActivityLogWidgetEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogWidgetEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity();
            }
            else if("ActivityLogWorkspaceEntity".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ActivityLogWorkspaceEntity = new global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ActivityLogFileEntity != null)
            {
                return ActivityLogFileEntity.GetFieldDeserializers();
            }
            else if(ActivityLogFileRepoEntity != null)
            {
                return ActivityLogFileRepoEntity.GetFieldDeserializers();
            }
            else if(ActivityLogOrgEntity != null)
            {
                return ActivityLogOrgEntity.GetFieldDeserializers();
            }
            else if(ActivityLogPluginEntity != null)
            {
                return ActivityLogPluginEntity.GetFieldDeserializers();
            }
            else if(ActivityLogProjectEntity != null)
            {
                return ActivityLogProjectEntity.GetFieldDeserializers();
            }
            else if(ActivityLogTeamEntity != null)
            {
                return ActivityLogTeamEntity.GetFieldDeserializers();
            }
            else if(ActivityLogUserEntity != null)
            {
                return ActivityLogUserEntity.GetFieldDeserializers();
            }
            else if(ActivityLogWidgetEntity != null)
            {
                return ActivityLogWidgetEntity.GetFieldDeserializers();
            }
            else if(ActivityLogWorkspaceEntity != null)
            {
                return ActivityLogWorkspaceEntity.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ActivityLogFileEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileEntity>(null, ActivityLogFileEntity);
            }
            else if(ActivityLogFileRepoEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogFileRepoEntity>(null, ActivityLogFileRepoEntity);
            }
            else if(ActivityLogOrgEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogOrgEntity>(null, ActivityLogOrgEntity);
            }
            else if(ActivityLogPluginEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogPluginEntity>(null, ActivityLogPluginEntity);
            }
            else if(ActivityLogProjectEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogProjectEntity>(null, ActivityLogProjectEntity);
            }
            else if(ActivityLogTeamEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogTeamEntity>(null, ActivityLogTeamEntity);
            }
            else if(ActivityLogUserEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogUserEntity>(null, ActivityLogUserEntity);
            }
            else if(ActivityLogWidgetEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWidgetEntity>(null, ActivityLogWidgetEntity);
            }
            else if(ActivityLogWorkspaceEntity != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ActivityLogWorkspaceEntity>(null, ActivityLogWorkspaceEntity);
            }
        }
    }
}
#pragma warning restore CS0618
