// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of entity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActivityLogWidgetEntityType
    {
        [EnumMember(Value = "widget")]
        #pragma warning disable CS1591
        Widget,
        #pragma warning restore CS1591
    }
}
