// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// A single per-user, per-day AI credit usage aggregate for the plan.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiUsageDailyRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The calendar date (UTC) of the aggregated usage, in `YYYY-MM-DD` format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Day { get; set; }
#nullable restore
#else
        public string Day { get; set; }
#endif
        /// <summary>The editor the AI action was associated with. `not_applicable` when the underlying AI action had no associated file.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRowEditorType? EditorType { get; set; }
        /// <summary>The id of the license group the usage was attributed to, or `null` when the usage had no associated license group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicenseGroupId { get; set; }
#nullable restore
#else
        public string LicenseGroupId { get; set; }
#endif
        /// <summary>The name of the license group the usage was attributed to, or `null` when the usage had no associated license group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicenseGroupName { get; set; }
#nullable restore
#else
        public string LicenseGroupName { get; set; }
#endif
        /// <summary>The end of the plan-scoped metering period this usage belongs to, as an RFC 3339 UTC timestamp (e.g. `2026-06-01T00:00:00Z`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeteringPeriodEnd { get; set; }
#nullable restore
#else
        public string MeteringPeriodEnd { get; set; }
#endif
        /// <summary>The start of the plan-scoped metering period this usage belongs to, as an RFC 3339 UTC timestamp (e.g. `2026-05-01T00:00:00Z`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeteringPeriodStart { get; set; }
#nullable restore
#else
        public string MeteringPeriodStart { get; set; }
#endif
        /// <summary>The sum of plan-level (shared pool) credits consumed for this day, user, and editor type.</summary>
        public int? PlanCreditsSum { get; set; }
        /// <summary>The id of the plan the usage belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>The sum of seat-level (per-user-allocated) credits consumed for this day, user, and editor type.</summary>
        public int? SeatCreditsSum { get; set; }
        /// <summary>The id of the team the usage was attributed to, or `null` when the usage had no associated team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The name of the team the usage was attributed to, or `null` when the usage had no associated team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamName { get; set; }
#nullable restore
#else
        public string TeamName { get; set; }
#endif
        /// <summary>The email of the Figma user that consumed the credits, or `null` when the user&apos;s email could not be resolved (e.g. a deleted user).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserEmail { get; set; }
#nullable restore
#else
        public string UserEmail { get; set; }
#endif
        /// <summary>The id of the Figma user that consumed the credits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The id of the workspace the usage was attributed to, or `null` when the usage had no associated workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceId { get; set; }
#nullable restore
#else
        public string WorkspaceId { get; set; }
#endif
        /// <summary>The name of the workspace the usage was attributed to, or `null` when the usage had no associated workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceName { get; set; }
#nullable restore
#else
        public string WorkspaceName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRow"/> and sets the default values.
        /// </summary>
        public AiUsageDailyRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "day", n => { Day = n.GetStringValue(); } },
                { "editor_type", n => { EditorType = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRowEditorType>(); } },
                { "license_group_id", n => { LicenseGroupId = n.GetStringValue(); } },
                { "license_group_name", n => { LicenseGroupName = n.GetStringValue(); } },
                { "metering_period_end", n => { MeteringPeriodEnd = n.GetStringValue(); } },
                { "metering_period_start", n => { MeteringPeriodStart = n.GetStringValue(); } },
                { "plan_credits_sum", n => { PlanCreditsSum = n.GetIntValue(); } },
                { "plan_id", n => { PlanId = n.GetStringValue(); } },
                { "seat_credits_sum", n => { SeatCreditsSum = n.GetIntValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "team_name", n => { TeamName = n.GetStringValue(); } },
                { "user_email", n => { UserEmail = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetStringValue(); } },
                { "workspace_name", n => { WorkspaceName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("day", Day);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.AiUsageDailyRowEditorType>("editor_type", EditorType);
            writer.WriteStringValue("license_group_id", LicenseGroupId);
            writer.WriteStringValue("license_group_name", LicenseGroupName);
            writer.WriteStringValue("metering_period_end", MeteringPeriodEnd);
            writer.WriteStringValue("metering_period_start", MeteringPeriodStart);
            writer.WriteIntValue("plan_credits_sum", PlanCreditsSum);
            writer.WriteStringValue("plan_id", PlanId);
            writer.WriteIntValue("seat_credits_sum", SeatCreditsSum);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("team_name", TeamName);
            writer.WriteStringValue("user_email", UserEmail);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("workspace_id", WorkspaceId);
            writer.WriteStringValue("workspace_name", WorkspaceName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
