// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of this node, represented by the string literal &quot;BOOLEAN_OPERATION&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BooleanOperationType
    {
        [EnumMember(Value = "BOOLEAN_OPERATION")]
        #pragma warning disable CS1591
        BooleanOperation,
        #pragma warning restore CS1591
    }
}
