// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CanvasNode : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An RGBA color</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Rgba? BackgroundColor { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Rgba BackgroundColor { get; set; }
#endif
        /// <summary>A mapping of field to the variables applied to this field. Most fields will only map to a single `VariableAlias`. However, for properties like `fills`, `strokes`, `size`, `componentProperties`, and `textRangeFills`, it is possible to have multiple variables bound to the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables? BoundVariables { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables BoundVariables { get; set; }
#endif
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode>? Children { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode> Children { get; set; }
#endif
        /// <summary>A mapping of a layer&apos;s property to component property name of component properties attached to this node. The component property name can be used to look up more information on the corresponding component&apos;s or component set&apos;s componentPropertyDefinitions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeComponentPropertyReferences? ComponentPropertyReferences { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeComponentPropertyReferences ComponentPropertyReferences { get; set; }
#endif
        /// <summary>A mapping of variable collection ID to mode ID representing the explicitly set modes for this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeExplicitVariableModes? ExplicitVariableModes { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeExplicitVariableModes ExplicitVariableModes { get; set; }
#endif
        /// <summary>An array of export settings representing images to export from the node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>? ExportSettings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting> ExportSettings { get; set; }
#endif
        /// <summary>An array of flow starting points sorted by its position in the prototype settings panel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.FlowStartingPoint>? FlowStartingPoints { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.FlowStartingPoint> FlowStartingPoints { get; set; }
#endif
        /// <summary>A string uniquely identifying this node within the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the layer is fixed while the parent is scrolling</summary>
        [Obsolete("")]
        public bool? IsFixed { get; set; }
        /// <summary>If true, layer is locked and cannot be edited</summary>
        public bool? Locked { get; set; }
        /// <summary>The measurements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Measurement>? Measurements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Measurement> Measurements { get; set; }
#endif
        /// <summary>The name given to the node by the user in the tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The background color of the prototype (currently only supports a single solid color paint).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Rgba>? PrototypeBackgrounds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Rgba> PrototypeBackgrounds { get; set; }
#endif
        /// <summary>The device used to view a prototype.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.PrototypeDevice? PrototypeDevice { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.PrototypeDevice PrototypeDevice { get; set; }
#endif
        /// <summary>Node ID that corresponds to the start frame for prototypes. This is deprecated with the introduction of multiple flows. Please use the `flowStartingPoints` field.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrototypeStartNodeID { get; set; }
#nullable restore
#else
        public string PrototypeStartNodeID { get; set; }
#endif
        /// <summary>The rotation of the node, if not 0.</summary>
        public double? Rotation { get; set; }
        /// <summary>How layer should be treated when the frame is resized</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior? ScrollBehavior { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.CanvasType? Type { get; set; }
        /// <summary>Whether or not the node is visible on the canvas.</summary>
        public bool? Visible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.CanvasNode"/> and sets the default values.
        /// </summary>
        public CanvasNode()
        {
            AdditionalData = new Dictionary<string, object>();
            IsFixed = false;
            Locked = false;
            Rotation = 0;
            Visible = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.CanvasNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.CanvasNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.CanvasNode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backgroundColor", n => { BackgroundColor = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rgba>(global::Soenneker.Figma.OpenApiClient.Models.Rgba.CreateFromDiscriminatorValue); } },
                { "boundVariables", n => { BoundVariables = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables>(global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables.CreateFromDiscriminatorValue); } },
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode>(global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode.CreateFromDiscriminatorValue)?.AsList(); } },
                { "componentPropertyReferences", n => { ComponentPropertyReferences = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeComponentPropertyReferences>(global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeComponentPropertyReferences.CreateFromDiscriminatorValue); } },
                { "explicitVariableModes", n => { ExplicitVariableModes = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeExplicitVariableModes>(global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeExplicitVariableModes.CreateFromDiscriminatorValue); } },
                { "exportSettings", n => { ExportSettings = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>(global::Soenneker.Figma.OpenApiClient.Models.ExportSetting.CreateFromDiscriminatorValue)?.AsList(); } },
                { "flowStartingPoints", n => { FlowStartingPoints = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.FlowStartingPoint>(global::Soenneker.Figma.OpenApiClient.Models.FlowStartingPoint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isFixed", n => { IsFixed = n.GetBoolValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "measurements", n => { Measurements = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Measurement>(global::Soenneker.Figma.OpenApiClient.Models.Measurement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "prototypeBackgrounds", n => { PrototypeBackgrounds = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Rgba>(global::Soenneker.Figma.OpenApiClient.Models.Rgba.CreateFromDiscriminatorValue)?.AsList(); } },
                { "prototypeDevice", n => { PrototypeDevice = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.PrototypeDevice>(global::Soenneker.Figma.OpenApiClient.Models.PrototypeDevice.CreateFromDiscriminatorValue); } },
                { "prototypeStartNodeID", n => { PrototypeStartNodeID = n.GetStringValue(); } },
                { "rotation", n => { Rotation = n.GetDoubleValue(); } },
                { "scrollBehavior", n => { ScrollBehavior = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasType>(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rgba>("backgroundColor", BackgroundColor);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables>("boundVariables", BoundVariables);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode>("children", Children);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeComponentPropertyReferences>("componentPropertyReferences", ComponentPropertyReferences);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasNodeExplicitVariableModes>("explicitVariableModes", ExplicitVariableModes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>("exportSettings", ExportSettings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.FlowStartingPoint>("flowStartingPoints", FlowStartingPoints);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isFixed", IsFixed);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Measurement>("measurements", Measurements);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Rgba>("prototypeBackgrounds", PrototypeBackgrounds);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.PrototypeDevice>("prototypeDevice", PrototypeDevice);
            writer.WriteStringValue("prototypeStartNodeID", PrototypeStartNodeID);
            writer.WriteDoubleValue("rotation", Rotation);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior>("scrollBehavior", ScrollBehavior);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.CanvasType>("type", Type);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
