// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CanvasType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CANVAS")]
        #pragma warning disable CS1591
        Canvas,
        #pragma warning restore CS1591
    }
}
