// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// A comment or reply left by a user.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Comment : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Positioning information of the comment. Includes information on the location of the comment pin, which is either the absolute coordinates on the canvas or a relative offset within a frame. If the comment is a region, it will also contain the region height, width, and position of the anchor in regards to the region.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta? ClientMeta { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta ClientMeta { get; set; }
#endif
        /// <summary>The UTC ISO 8601 time at which the comment was left</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The file in which the comment lives</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileKey { get; set; }
#nullable restore
#else
        public string FileKey { get; set; }
#endif
        /// <summary>Unique identifier for comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The content of the comment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Only set for top level comments. The number displayed with the comment in the UI</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderId { get; set; }
#nullable restore
#else
        public string OrderId { get; set; }
#endif
        /// <summary>If present, the id of the comment to which this is the reply</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>An array of reactions to the comment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Reaction>? Reactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Reaction> Reactions { get; set; }
#endif
        /// <summary>If set, the UTC ISO 8601 time the comment was resolved</summary>
        public DateTimeOffset? ResolvedAt { get; set; }
        /// <summary>The user who left the comment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.User? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.Comment"/> and sets the default values.
        /// </summary>
        public Comment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.Comment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.Comment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.Comment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_meta", n => { ClientMeta = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta>(global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "file_key", n => { FileKey = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "order_id", n => { OrderId = n.GetStringValue(); } },
                { "parent_id", n => { ParentId = n.GetStringValue(); } },
                { "reactions", n => { Reactions = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Reaction>(global::Soenneker.Figma.OpenApiClient.Models.Reaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resolved_at", n => { ResolvedAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.User>(global::Soenneker.Figma.OpenApiClient.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta>("client_meta", ClientMeta);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("file_key", FileKey);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("order_id", OrderId);
            writer.WriteStringValue("parent_id", ParentId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Reaction>("reactions", Reactions);
            writer.WriteDateTimeOffsetValue("resolved_at", ResolvedAt);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
