// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameOffset"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.Region"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.Vector"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommentClientMeta : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameOffset"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.FrameOffset? FrameOffset { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.FrameOffset FrameOffset { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion? FrameOffsetRegion { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion FrameOffsetRegion { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.Region"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Region? Region { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Region Region { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.Vector"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Vector? Vector { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Vector Vector { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Figma.OpenApiClient.Models.CommentClientMeta();
            if("FrameOffset".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FrameOffset = new global::Soenneker.Figma.OpenApiClient.Models.FrameOffset();
            }
            else if("FrameOffsetRegion".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FrameOffsetRegion = new global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion();
            }
            else if("Region".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Region = new global::Soenneker.Figma.OpenApiClient.Models.Region();
            }
            else if("Vector".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Vector = new global::Soenneker.Figma.OpenApiClient.Models.Vector();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FrameOffset != null)
            {
                return FrameOffset.GetFieldDeserializers();
            }
            else if(FrameOffsetRegion != null)
            {
                return FrameOffsetRegion.GetFieldDeserializers();
            }
            else if(Region != null)
            {
                return Region.GetFieldDeserializers();
            }
            else if(Vector != null)
            {
                return Vector.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(FrameOffset != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.FrameOffset>(null, FrameOffset);
            }
            else if(FrameOffsetRegion != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.FrameOffsetRegion>(null, FrameOffsetRegion);
            }
            else if(Region != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Region>(null, Region);
            }
            else if(Vector != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Vector>(null, Vector);
            }
        }
    }
}
#pragma warning restore CS0618
