// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Connector line type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConnectorLineType
    {
        [EnumMember(Value = "STRAIGHT")]
        #pragma warning disable CS1591
        Straight,
        #pragma warning restore CS1591
        [EnumMember(Value = "ELBOWED")]
        #pragma warning disable CS1591
        Elbowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURVED")]
        #pragma warning disable CS1591
        Curved,
        #pragma warning restore CS1591
    }
}
