// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Connector text background.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectorTextBackground : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Radius of each corner if a single radius is set for all corners</summary>
        public double? CornerRadius { get; set; }
        /// <summary>A value that lets you control how &quot;smooth&quot; the corners are. Ranges from 0 to 1. 0 is the default and means that the corner is perfectly circular. A value of 0.6 means the corner matches the iOS 7 &quot;squircle&quot; icon shape. Other values produce various other curves.</summary>
        public double? CornerSmoothing { get; set; }
        /// <summary>An array of fill paints applied to the node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint>? Fills { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint> Fills { get; set; }
#endif
        /// <summary>Array of length 4 of the radius of each corner of the frame, starting in the top left and proceeding clockwise.Values are given in the order top-left, top-right, bottom-right, bottom-left.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? RectangleCornerRadii { get; set; }
#nullable restore
#else
        public List<double?> RectangleCornerRadii { get; set; }
#endif
        /// <summary>A mapping of a StyleType to style ID (see Style) of styles present on this node. The style ID can be used to look up more information about the style in the top-level styles field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackgroundStyles? Styles { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackgroundStyles Styles { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackground"/> and sets the default values.
        /// </summary>
        public ConnectorTextBackground()
        {
            AdditionalData = new Dictionary<string, object>();
            CornerRadius = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackground"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackground CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackground();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cornerRadius", n => { CornerRadius = n.GetDoubleValue(); } },
                { "cornerSmoothing", n => { CornerSmoothing = n.GetDoubleValue(); } },
                { "fills", n => { Fills = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>(global::Soenneker.Figma.OpenApiClient.Models.Paint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rectangleCornerRadii", n => { RectangleCornerRadii = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "styles", n => { Styles = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackgroundStyles>(global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackgroundStyles.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("cornerRadius", CornerRadius);
            writer.WriteDoubleValue("cornerSmoothing", CornerSmoothing);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>("fills", Fills);
            writer.WriteCollectionOfPrimitiveValues<double?>("rectangleCornerRadii", RectangleCornerRadii);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ConnectorTextBackgroundStyles>("styles", Styles);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
