// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Type of constraint to apply:- `SCALE`: Scale by `value`.- `WIDTH`: Scale proportionally and set width to `value`.- `HEIGHT`: Scale proportionally and set height to `value`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConstraintType
    {
        [EnumMember(Value = "SCALE")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
        [EnumMember(Value = "WIDTH")]
        #pragma warning disable CS1591
        Width,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEIGHT")]
        #pragma warning disable CS1591
        Height,
        #pragma warning restore CS1591
    }
}
