// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The action to perform for the variable collection.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateAction
    {
        [EnumMember(Value = "CREATE")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
    }
}
