// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of resource; null for requests without an associated resource (e.g. activity logs).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeveloperLogResourceType
    {
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
        [EnumMember(Value = "team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
    }
}
