// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The easing curve used in the prototyping transition on this node.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EasingType
    {
        [EnumMember(Value = "EASE_IN")]
        #pragma warning disable CS1591
        EaseIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "EASE_OUT")]
        #pragma warning disable CS1591
        EaseOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "EASE_IN_AND_OUT")]
        #pragma warning disable CS1591
        EaseInAndOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "LINEAR")]
        #pragma warning disable CS1591
        Linear,
        #pragma warning restore CS1591
        [EnumMember(Value = "EASE_IN_BACK")]
        #pragma warning disable CS1591
        EaseInBack,
        #pragma warning restore CS1591
        [EnumMember(Value = "EASE_OUT_BACK")]
        #pragma warning disable CS1591
        EaseOutBack,
        #pragma warning restore CS1591
        [EnumMember(Value = "EASE_IN_AND_OUT_BACK")]
        #pragma warning disable CS1591
        EaseInAndOutBack,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_CUBIC_BEZIER")]
        #pragma warning disable CS1591
        CustomCubicBezier,
        #pragma warning restore CS1591
        [EnumMember(Value = "GENTLE")]
        #pragma warning disable CS1591
        Gentle,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUICK")]
        #pragma warning disable CS1591
        Quick,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOUNCY")]
        #pragma warning disable CS1591
        Bouncy,
        #pragma warning restore CS1591
        [EnumMember(Value = "SLOW")]
        #pragma warning disable CS1591
        Slow,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_SPRING")]
        #pragma warning disable CS1591
        CustomSpring,
        #pragma warning restore CS1591
    }
}
