// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExportSettingFormat
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "JPG")]
        #pragma warning disable CS1591
        Jpg,
        #pragma warning restore CS1591
        [EnumMember(Value = "PNG")]
        #pragma warning disable CS1591
        Png,
        #pragma warning restore CS1591
        [EnumMember(Value = "SVG")]
        #pragma warning disable CS1591
        Svg,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
    }
}
