// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Defines the list of operators available to use in an Expression.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExpressionFunction
    {
        [EnumMember(Value = "ADDITION")]
        #pragma warning disable CS1591
        Addition,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBTRACTION")]
        #pragma warning disable CS1591
        Subtraction,
        #pragma warning restore CS1591
        [EnumMember(Value = "MULTIPLICATION")]
        #pragma warning disable CS1591
        Multiplication,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIVISION")]
        #pragma warning disable CS1591
        Division,
        #pragma warning restore CS1591
        [EnumMember(Value = "EQUALS")]
        #pragma warning disable CS1591
        Equals,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_EQUAL")]
        #pragma warning disable CS1591
        NotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "LESS_THAN")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "LESS_THAN_OR_EQUAL")]
        #pragma warning disable CS1591
        LessThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "GREATER_THAN")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "GREATER_THAN_OR_EQUAL")]
        #pragma warning disable CS1591
        GreaterThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "AND")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
        [EnumMember(Value = "OR")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
        [EnumMember(Value = "VAR_MODE_LOOKUP")]
        #pragma warning disable CS1591
        VarModeLookup,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEGATE")]
        #pragma warning disable CS1591
        Negate,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT")]
        #pragma warning disable CS1591
        Not,
        #pragma warning restore CS1591
    }
}
