// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of this node, represented by the string literal &quot;FRAME&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FrameType
    {
        [EnumMember(Value = "FRAME")]
        #pragma warning disable CS1591
        Frame,
        #pragma warning restore CS1591
    }
}
