// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetLibraryAnalyticsVariableUsagesGroupByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "variable")]
        #pragma warning disable CS1591
        Variable,
        #pragma warning restore CS1591
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
    }
}
