// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes List&lt;global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset&gt;, List&lt;global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetLibraryAnalyticsComponentActionsResponseResponseRows : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type List&lt;global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset>? LibraryAnalyticsComponentActionsByAsset { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset> LibraryAnalyticsComponentActionsByAsset { get; set; }
#endif
        /// <summary>Composed type representation for type List&lt;global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam>? LibraryAnalyticsComponentActionsByTeam { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam> LibraryAnalyticsComponentActionsByTeam { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponseRows"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponseRows CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Figma.OpenApiClient.Models.GetLibraryAnalyticsComponentActionsResponseResponseRows();
            if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset>(global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset> libraryAnalyticsComponentActionsByAssetValue)
            {
                result.LibraryAnalyticsComponentActionsByAsset = libraryAnalyticsComponentActionsByAssetValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam>(global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam> libraryAnalyticsComponentActionsByTeamValue)
            {
                result.LibraryAnalyticsComponentActionsByTeam = libraryAnalyticsComponentActionsByTeamValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(LibraryAnalyticsComponentActionsByAsset != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByAsset>(null, LibraryAnalyticsComponentActionsByAsset);
            }
            else if(LibraryAnalyticsComponentActionsByTeam != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.LibraryAnalyticsComponentActionsByTeam>(null, LibraryAnalyticsComponentActionsByTeam);
            }
        }
    }
}
#pragma warning restore CS0618
