// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Determines how the auto-layout frame&apos;s children should be aligned in the counter axis direction. This property is only applicable for auto-layout frames.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HasFramePropertiesTraitCounterAxisAlignItems
    {
        [EnumMember(Value = "MIN")]
        #pragma warning disable CS1591
        Min,
        #pragma warning restore CS1591
        [EnumMember(Value = "CENTER")]
        #pragma warning disable CS1591
        Center,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX")]
        #pragma warning disable CS1591
        Max,
        #pragma warning restore CS1591
        [EnumMember(Value = "BASELINE")]
        #pragma warning disable CS1591
        Baseline,
        #pragma warning restore CS1591
    }
}
