// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Determines how the auto-layout frame’s wrapped tracks should be aligned in the counter axis direction. This property is only applicable for auto-layout frames with `layoutWrap: &quot;WRAP&quot;`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HasFramePropertiesTraitCounterAxisAlignContent
    {
        [EnumMember(Value = "AUTO")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPACE_BETWEEN")]
        #pragma warning disable CS1591
        SpaceBetween,
        #pragma warning restore CS1591
    }
}
