// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>A string enum with value of &quot;MITER&quot;, &quot;BEVEL&quot;, or &quot;ROUND&quot;, describing how corners in vector paths are rendered.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HasGeometryTraitStrokeJoin
    {
        [EnumMember(Value = "MITER")]
        #pragma warning disable CS1591
        Miter,
        #pragma warning restore CS1591
        [EnumMember(Value = "BEVEL")]
        #pragma warning disable CS1591
        Bevel,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROUND")]
        #pragma warning disable CS1591
        Round,
        #pragma warning restore CS1591
    }
}
