// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Determines whether a layer&apos;s size and position should be determined by auto-layout settings or manually adjustable.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HasLayoutTraitLayoutPositioning
    {
        [EnumMember(Value = "AUTO")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABSOLUTE")]
        #pragma warning disable CS1591
        Absolute,
        #pragma warning restore CS1591
    }
}
