// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Image filters to apply to the node.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageFilters : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contrast property</summary>
        public double? Contrast { get; set; }
        /// <summary>The exposure property</summary>
        public double? Exposure { get; set; }
        /// <summary>The highlights property</summary>
        public double? Highlights { get; set; }
        /// <summary>The saturation property</summary>
        public double? Saturation { get; set; }
        /// <summary>The shadows property</summary>
        public double? Shadows { get; set; }
        /// <summary>The temperature property</summary>
        public double? Temperature { get; set; }
        /// <summary>The tint property</summary>
        public double? Tint { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.ImageFilters"/> and sets the default values.
        /// </summary>
        public ImageFilters()
        {
            AdditionalData = new Dictionary<string, object>();
            Contrast = 0;
            Exposure = 0;
            Highlights = 0;
            Saturation = 0;
            Shadows = 0;
            Temperature = 0;
            Tint = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.ImageFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.ImageFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.ImageFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contrast", n => { Contrast = n.GetDoubleValue(); } },
                { "exposure", n => { Exposure = n.GetDoubleValue(); } },
                { "highlights", n => { Highlights = n.GetDoubleValue(); } },
                { "saturation", n => { Saturation = n.GetDoubleValue(); } },
                { "shadows", n => { Shadows = n.GetDoubleValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "tint", n => { Tint = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("contrast", Contrast);
            writer.WriteDoubleValue("exposure", Exposure);
            writer.WriteDoubleValue("highlights", Highlights);
            writer.WriteDoubleValue("saturation", Saturation);
            writer.WriteDoubleValue("shadows", Shadows);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteDoubleValue("tint", Tint);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
