// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>How layer should be treated when the frame is resized</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IsLayerTraitScrollBehavior
    {
        [EnumMember(Value = "SCROLLS")]
        #pragma warning disable CS1591
        Scrolls,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIXED")]
        #pragma warning disable CS1591
        FixedValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "STICKY_SCROLLS")]
        #pragma warning disable CS1591
        StickyScrolls,
        #pragma warning restore CS1591
    }
}
