// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Vertical constraint (relative to containing frame) as an enum:- `TOP`: Node is laid out relative to top of the containing frame- `BOTTOM`: Node is laid out relative to bottom of the containing frame- `CENTER`: Node is vertically centered relative to containing frame- `TOP_BOTTOM`: Both top and bottom of node are constrained relative to containing frame (node stretches with frame)- `SCALE`: Node scales vertically with containing frame</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LayoutConstraintVertical
    {
        [EnumMember(Value = "TOP")]
        #pragma warning disable CS1591
        Top,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOTTOM")]
        #pragma warning disable CS1591
        Bottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "CENTER")]
        #pragma warning disable CS1591
        Center,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOP_BOTTOM")]
        #pragma warning disable CS1591
        TopBottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCALE")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
    }
}
