// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Horizontal constraint (relative to containing frame) as an enum:- `LEFT`: Node is laid out relative to left of the containing frame- `RIGHT`: Node is laid out relative to right of the containing frame- `CENTER`: Node is horizontally centered relative to containing frame- `LEFT_RIGHT`: Both left and right of node are constrained relative to containing frame (node stretches with frame)- `SCALE`: Node scales horizontally with containing frame</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LayoutConstraintHorizontal
    {
        [EnumMember(Value = "LEFT")]
        #pragma warning disable CS1591
        Left,
        #pragma warning restore CS1591
        [EnumMember(Value = "RIGHT")]
        #pragma warning disable CS1591
        Right,
        #pragma warning restore CS1591
        [EnumMember(Value = "CENTER")]
        #pragma warning disable CS1591
        Center,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEFT_RIGHT")]
        #pragma warning disable CS1591
        LeftRight,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCALE")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
    }
}
