// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeasurementOffset : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner? MeasurementOffsetInner { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner MeasurementOffsetInner { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter? MeasurementOffsetOuter { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter MeasurementOffsetOuter { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset();
            if("MeasurementOffsetInner".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MeasurementOffsetInner = new global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner();
            }
            else if("MeasurementOffsetOuter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MeasurementOffsetOuter = new global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MeasurementOffsetInner != null)
            {
                return MeasurementOffsetInner.GetFieldDeserializers();
            }
            else if(MeasurementOffsetOuter != null)
            {
                return MeasurementOffsetOuter.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MeasurementOffsetInner != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetInner>(null, MeasurementOffsetInner);
            }
            else if(MeasurementOffsetOuter != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffsetOuter>(null, MeasurementOffsetOuter);
            }
        }
    }
}
#pragma warning restore CS0618
