// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// A pinned distance between two nodes in Dev Mode
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Measurement : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The node and side a measurement is pinned to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd? End { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd End { get; set; }
#endif
        /// <summary>When manually overridden, the displayed value of the measurement</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FreeText { get; set; }
#nullable restore
#else
        public string FreeText { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The offset property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset? Offset { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset Offset { get; set; }
#endif
        /// <summary>The node and side a measurement is pinned to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd? Start { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd Start { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.Measurement"/> and sets the default values.
        /// </summary>
        public Measurement()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.Measurement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.Measurement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.Measurement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end", n => { End = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd>(global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd.CreateFromDiscriminatorValue); } },
                { "freeText", n => { FreeText = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "offset", n => { Offset = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset>(global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset.CreateFromDiscriminatorValue); } },
                { "start", n => { Start = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd>(global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd>("end", End);
            writer.WriteStringValue("freeText", FreeText);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementOffset>("offset", Offset);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.MeasurementStartEnd>("start", Start);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
