// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OuterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OUTER")]
        #pragma warning disable CS1591
        Outer,
        #pragma warning restore CS1591
    }
}
