// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The string literal &quot;PATTERN&quot; representing the paint&apos;s type. Always check the `type` before reading other properties.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatternType
    {
        [EnumMember(Value = "PATTERN")]
        #pragma warning disable CS1591
        Pattern,
        #pragma warning restore CS1591
    }
}
