// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PrototypeDeviceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRESET")]
        #pragma warning disable CS1591
        Preset,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRESENTATION")]
        #pragma warning disable CS1591
        Presentation,
        #pragma warning restore CS1591
    }
}
