// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of this node, represented by the string literal &quot;RECTANGLE&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RectangleType
    {
        [EnumMember(Value = "RECTANGLE")]
        #pragma warning disable CS1591
        Rectangle,
        #pragma warning restore CS1591
    }
}
