// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// An RGBA color
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Rgba : IAdditionalDataHolder, IParsable
    {
        /// <summary>Alpha channel value, between 0 and 1.</summary>
        public double? A { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Blue channel value, between 0 and 1.</summary>
        public double? B { get; set; }
        /// <summary>Green channel value, between 0 and 1.</summary>
        public double? G { get; set; }
        /// <summary>Red channel value, between 0 and 1.</summary>
        public double? R { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.Rgba"/> and sets the default values.
        /// </summary>
        public Rgba()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.Rgba"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.Rgba CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.Rgba();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "a", n => { A = n.GetDoubleValue(); } },
                { "b", n => { B = n.GetDoubleValue(); } },
                { "g", n => { G = n.GetDoubleValue(); } },
                { "r", n => { R = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("a", A);
            writer.WriteDoubleValue("b", B);
            writer.WriteDoubleValue("g", G);
            writer.WriteDoubleValue("r", R);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
