// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The type of this node, represented by the string literal &quot;SECTION&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SectionType
    {
        [EnumMember(Value = "SECTION")]
        #pragma warning disable CS1591
        Section,
        #pragma warning restore CS1591
    }
}
