// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SetVariableType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SET_VARIABLE")]
        #pragma warning disable CS1591
        SetVariable,
        #pragma warning restore CS1591
    }
}
