// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Geometric shape type. Most shape types have the same name as their tooltip but there are a few exceptions. ENG_DATABASE: Cylinder, ENG_QUEUE: Horizontal cylinder, ENG_FILE: File, ENG_FOLDER: Folder.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShapeType
    {
        [EnumMember(Value = "SQUARE")]
        #pragma warning disable CS1591
        Square,
        #pragma warning restore CS1591
        [EnumMember(Value = "ELLIPSE")]
        #pragma warning disable CS1591
        Ellipse,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROUNDED_RECTANGLE")]
        #pragma warning disable CS1591
        RoundedRectangle,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIAMOND")]
        #pragma warning disable CS1591
        Diamond,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIANGLE_UP")]
        #pragma warning disable CS1591
        TriangleUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRIANGLE_DOWN")]
        #pragma warning disable CS1591
        TriangleDown,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARALLELOGRAM_RIGHT")]
        #pragma warning disable CS1591
        ParallelogramRight,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARALLELOGRAM_LEFT")]
        #pragma warning disable CS1591
        ParallelogramLeft,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENG_DATABASE")]
        #pragma warning disable CS1591
        EngDatabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENG_QUEUE")]
        #pragma warning disable CS1591
        EngQueue,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENG_FILE")]
        #pragma warning disable CS1591
        EngFile,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENG_FOLDER")]
        #pragma warning disable CS1591
        EngFolder,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAPEZOID")]
        #pragma warning disable CS1591
        Trapezoid,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREDEFINED_PROCESS")]
        #pragma warning disable CS1591
        PredefinedProcess,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHIELD")]
        #pragma warning disable CS1591
        Shield,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_SINGLE")]
        #pragma warning disable CS1591
        DocumentSingle,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_MULTIPLE")]
        #pragma warning disable CS1591
        DocumentMultiple,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL_INPUT")]
        #pragma warning disable CS1591
        ManualInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEXAGON")]
        #pragma warning disable CS1591
        Hexagon,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHEVRON")]
        #pragma warning disable CS1591
        Chevron,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENTAGON")]
        #pragma warning disable CS1591
        Pentagon,
        #pragma warning restore CS1591
        [EnumMember(Value = "OCTAGON")]
        #pragma warning disable CS1591
        Octagon,
        #pragma warning restore CS1591
        [EnumMember(Value = "STAR")]
        #pragma warning disable CS1591
        Star,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLUS")]
        #pragma warning disable CS1591
        Plus,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARROW_LEFT")]
        #pragma warning disable CS1591
        ArrowLeft,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARROW_RIGHT")]
        #pragma warning disable CS1591
        ArrowRight,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUMMING_JUNCTION")]
        #pragma warning disable CS1591
        SummingJunction,
        #pragma warning restore CS1591
        [EnumMember(Value = "OR")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPEECH_BUBBLE")]
        #pragma warning disable CS1591
        SpeechBubble,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL_STORAGE")]
        #pragma warning disable CS1591
        InternalStorage,
        #pragma warning restore CS1591
    }
}
