// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShapeWithTextNode : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Bounding box of the node in absolute space coordinates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Rectangle? AbsoluteBoundingBox { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Rectangle AbsoluteBoundingBox { get; set; }
#endif
        /// <summary>The actual bounds of a node accounting for drop shadows, thick strokes, and anything else that may fall outside the node&apos;s regular bounding box defined in `x`, `y`, `width`, and `height`. The `x` and `y` inside this property represent the absolute position of the node on the page. This value will be `null` if the node is invisible.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Rectangle? AbsoluteRenderBounds { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Rectangle AbsoluteRenderBounds { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How this node blends with nodes behind it in the scene (see blend mode section for more details)</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.BlendMode? BlendMode { get; set; }
        /// <summary>A mapping of field to the variables applied to this field. Most fields will only map to a single `VariableAlias`. However, for properties like `fills`, `strokes`, `size`, `componentProperties`, and `textRangeFills`, it is possible to have multiple variables bound to the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables? BoundVariables { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables BoundVariables { get; set; }
#endif
        /// <summary>Text contained within a text box.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Characters { get; set; }
#nullable restore
#else
        public string Characters { get; set; }
#endif
        /// <summary>A mapping of a layer&apos;s property to component property name of component properties attached to this node. The component property name can be used to look up more information on the corresponding component&apos;s or component set&apos;s componentPropertyDefinitions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeComponentPropertyReferences? ComponentPropertyReferences { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeComponentPropertyReferences ComponentPropertyReferences { get; set; }
#endif
        /// <summary>Horizontal and vertical layout constraints for node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.LayoutConstraint? Constraints { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.LayoutConstraint Constraints { get; set; }
#endif
        /// <summary>Radius of each corner if a single radius is set for all corners</summary>
        public double? CornerRadius { get; set; }
        /// <summary>A value that lets you control how &quot;smooth&quot; the corners are. Ranges from 0 to 1. 0 is the default and means that the corner is perfectly circular. A value of 0.6 means the corner matches the iOS 7 &quot;squircle&quot; icon shape. Other values produce various other curves.</summary>
        public double? CornerSmoothing { get; set; }
        /// <summary>An array of effects attached to this node (see effects section for more details)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Effect>? Effects { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Effect> Effects { get; set; }
#endif
        /// <summary>A mapping of variable collection ID to mode ID representing the explicitly set modes for this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeExplicitVariableModes? ExplicitVariableModes { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeExplicitVariableModes ExplicitVariableModes { get; set; }
#endif
        /// <summary>An array of export settings representing images to export from the node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>? ExportSettings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting> ExportSettings { get; set; }
#endif
        /// <summary>An array of fill paints applied to the node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint>? Fills { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint> Fills { get; set; }
#endif
        /// <summary>Determines how a GRID frame&apos;s child should be aligned in the horizontal direction within its grid area. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildHorizontalAlign? GridChildHorizontalAlign { get; set; }
        /// <summary>Determines how a GRID frame&apos;s child should be aligned in the vertical direction within its grid area. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildVerticalAlign? GridChildVerticalAlign { get; set; }
        /// <summary>The index of the column that a GRID frame&apos;s child should be anchored to. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridColumnAnchorIndex { get; set; }
        /// <summary>The number of columns in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridColumnCount { get; set; }
        /// <summary>The distance between columns in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridColumnGap { get; set; }
        /// <summary>The number of columns that a GRID frame&apos;s child should span. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridColumnSpan { get; set; }
        /// <summary>The string for the CSS grid-template-columns property. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridColumnsSizing { get; set; }
#nullable restore
#else
        public string GridColumnsSizing { get; set; }
#endif
        /// <summary>The index of the row that a GRID frame&apos;s child should be anchored to. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridRowAnchorIndex { get; set; }
        /// <summary>The number of rows in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridRowCount { get; set; }
        /// <summary>The distance between rows in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridRowGap { get; set; }
        /// <summary>The number of rows that a GRID frame&apos;s child should span. This property is only applicable for direct children of frames with `layoutMode: &quot;GRID&quot;`.</summary>
        public double? GridRowSpan { get; set; }
        /// <summary>The string for the CSS grid-template-rows property. This property is only applicable for auto-layout frames with `layoutMode: &quot;GRID&quot;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridRowsSizing { get; set; }
#nullable restore
#else
        public string GridRowsSizing { get; set; }
#endif
        /// <summary>A string uniquely identifying this node within the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the layer is fixed while the parent is scrolling</summary>
        [Obsolete("")]
        public bool? IsFixed { get; set; }
        /// <summary>Does this node mask sibling nodes in front of it?</summary>
        public bool? IsMask { get; set; }
        /// <summary>True if maskType is VECTOR. This field is deprecated; use maskType instead.</summary>
        [Obsolete("")]
        public bool? IsMaskOutline { get; set; }
        /// <summary>Determines if the layer should stretch along the parent&apos;s counter axis. This property is only provided for direct children of auto-layout frames.- `INHERIT`- `STRETCH`In previous versions of auto layout, determined how the layer is aligned inside an auto-layout frame. This property is only provided for direct children of auto-layout frames.- `MIN`- `CENTER`- `MAX`- `STRETCH`In horizontal auto-layout frames, &quot;MIN&quot; and &quot;MAX&quot; correspond to &quot;TOP&quot; and &quot;BOTTOM&quot;. In vertical auto-layout frames, &quot;MIN&quot; and &quot;MAX&quot; correspond to &quot;LEFT&quot; and &quot;RIGHT&quot;.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutAlign? LayoutAlign { get; set; }
        /// <summary>This property is applicable only for direct children of auto-layout frames, ignored otherwise. Determines whether a layer should stretch along the parent&apos;s primary axis. A `0` corresponds to a fixed size and `1` corresponds to stretch.</summary>
        public double? LayoutGrow { get; set; }
        /// <summary>Determines whether a layer&apos;s size and position should be determined by auto-layout settings or manually adjustable.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutPositioning? LayoutPositioning { get; set; }
        /// <summary>The horizontal sizing setting on this auto-layout frame or frame child.- `FIXED`- `HUG`: only valid on auto-layout frames and text nodes- `FILL`: only valid on auto-layout frame children</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingHorizontal? LayoutSizingHorizontal { get; set; }
        /// <summary>The vertical sizing setting on this auto-layout frame or frame child.- `FIXED`- `HUG`: only valid on auto-layout frames and text nodes- `FILL`: only valid on auto-layout frame children</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingVertical? LayoutSizingVertical { get; set; }
        /// <summary>If true, layer is locked and cannot be edited</summary>
        public bool? Locked { get; set; }
        /// <summary>If this layer is a mask, this property describes the operation used to mask the layer&apos;s siblings. The value may be one of the following:- ALPHA: the mask node&apos;s alpha channel will be used to determine the opacity of each pixel in the masked result.- VECTOR: if the mask node has visible fill paints, every pixel inside the node&apos;s fill regions will be fully visible in the masked result. If the mask has visible stroke paints, every pixel inside the node&apos;s stroke regions will be fully visible in the masked result.- LUMINANCE: the luminance value of each pixel of the mask node will be used to determine the opacity of that pixel in the masked result.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasMaskTraitMaskType? MaskType { get; set; }
        /// <summary>The maximum height of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.</summary>
        public double? MaxHeight { get; set; }
        /// <summary>The maximum width of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.</summary>
        public double? MaxWidth { get; set; }
        /// <summary>The minimum height of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.</summary>
        public double? MinHeight { get; set; }
        /// <summary>The minimum width of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.</summary>
        public double? MinWidth { get; set; }
        /// <summary>The name given to the node by the user in the tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Opacity of the node</summary>
        public double? Opacity { get; set; }
        /// <summary>Keep height and width constrained to same ratio.</summary>
        public bool? PreserveRatio { get; set; }
        /// <summary>Array of length 4 of the radius of each corner of the frame, starting in the top left and proceeding clockwise.Values are given in the order top-left, top-right, bottom-right, bottom-left.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? RectangleCornerRadii { get; set; }
#nullable restore
#else
        public List<double?> RectangleCornerRadii { get; set; }
#endif
        /// <summary>A transformation matrix is standard way in computer graphics to represent translation and rotation. These are the top two rows of a 3x3 matrix. The bottom row of the matrix is assumed to be [0, 0, 1]. This is known as an affine transform and is enough to represent translation, rotation, and skew.The identity transform is [[1, 0, 0], [0, 1, 0]].A translation matrix will typically look like:```[[1, 0, tx],  [0, 1, ty]]```and a rotation matrix will typically look like:```[[cos(angle), sin(angle), 0],  [-sin(angle), cos(angle), 0]]```Another way to think about this transform is as three vectors:- The x axis (t[0][0], t[1][0])- The y axis (t[0][1], t[1][1])- The translation offset (t[0][2], t[1][2])The most common usage of the Transform matrix is the `relativeTransform property`. This particular usage of the matrix has a few additional restrictions. The translation offset can take on any value but we do enforce that the axis vectors are unit vectors (i.e. have length 1). The axes are not required to be at 90° angles to each other.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RelativeTransform { get; set; }
#nullable restore
#else
        public UntypedNode RelativeTransform { get; set; }
#endif
        /// <summary>The rotation of the node, if not 0.</summary>
        public double? Rotation { get; set; }
        /// <summary>How layer should be treated when the frame is resized</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior? ScrollBehavior { get; set; }
        /// <summary>Geometric shape type. Most shape types have the same name as their tooltip but there are a few exceptions. ENG_DATABASE: Cylinder, ENG_QUEUE: Horizontal cylinder, ENG_FILE: File, ENG_FOLDER: Folder.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeType? ShapeType { get; set; }
        /// <summary>Width and height of element. This is different from the width and height of the bounding box in that the absolute bounding box represents the element after scaling and rotation. Only present if `geometry=paths` is passed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.Vector? Size { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.Vector Size { get; set; }
#endif
        /// <summary>Position of stroke relative to vector outline, as a string enum- `INSIDE`: stroke drawn inside the shape boundary- `OUTSIDE`: stroke drawn outside the shape boundary- `CENTER`: stroke drawn centered along the shape boundary</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeAlign? StrokeAlign { get; set; }
        /// <summary>An array of floating point numbers describing the pattern of dash length and gap lengths that the vector stroke will use when drawn.For example a value of [1, 2] indicates that the stroke will be drawn with a dash of length 1 followed by a gap of length 2, repeated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? StrokeDashes { get; set; }
#nullable restore
#else
        public List<double?> StrokeDashes { get; set; }
#endif
        /// <summary>A string enum with value of &quot;MITER&quot;, &quot;BEVEL&quot;, or &quot;ROUND&quot;, describing how corners in vector paths are rendered.</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeJoin? StrokeJoin { get; set; }
        /// <summary>An array of stroke paints applied to the node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint>? Strokes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Figma.OpenApiClient.Models.Paint> Strokes { get; set; }
#endif
        /// <summary>The weight of strokes on the node.</summary>
        public double? StrokeWeight { get; set; }
        /// <summary>A mapping of a StyleType to style ID (see Style) of styles present on this node. The style ID can be used to look up more information about the style in the top-level styles field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeStyles? Styles { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeStyles Styles { get; set; }
#endif
        /// <summary>The type of this node, represented by the string literal &quot;SHAPE_WITH_TEXT&quot;</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextType? Type { get; set; }
        /// <summary>Whether or not the node is visible on the canvas.</summary>
        public bool? Visible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode"/> and sets the default values.
        /// </summary>
        public ShapeWithTextNode()
        {
            AdditionalData = new Dictionary<string, object>();
            CornerRadius = 0;
            GridColumnAnchorIndex = 0;
            GridColumnGap = 0;
            GridColumnSpan = 1;
            GridRowAnchorIndex = 0;
            GridRowGap = 0;
            GridRowSpan = 1;
            IsFixed = false;
            IsMask = false;
            IsMaskOutline = false;
            LayoutGrow = 0;
            Locked = false;
            MaxHeight = 0;
            MaxWidth = 0;
            MinHeight = 0;
            MinWidth = 0;
            Opacity = 1;
            PreserveRatio = false;
            Rotation = 0;
            StrokeWeight = 1;
            Visible = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absoluteBoundingBox", n => { AbsoluteBoundingBox = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rectangle>(global::Soenneker.Figma.OpenApiClient.Models.Rectangle.CreateFromDiscriminatorValue); } },
                { "absoluteRenderBounds", n => { AbsoluteRenderBounds = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rectangle>(global::Soenneker.Figma.OpenApiClient.Models.Rectangle.CreateFromDiscriminatorValue); } },
                { "blendMode", n => { BlendMode = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.BlendMode>(); } },
                { "boundVariables", n => { BoundVariables = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables>(global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables.CreateFromDiscriminatorValue); } },
                { "characters", n => { Characters = n.GetStringValue(); } },
                { "componentPropertyReferences", n => { ComponentPropertyReferences = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeComponentPropertyReferences>(global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeComponentPropertyReferences.CreateFromDiscriminatorValue); } },
                { "constraints", n => { Constraints = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.LayoutConstraint>(global::Soenneker.Figma.OpenApiClient.Models.LayoutConstraint.CreateFromDiscriminatorValue); } },
                { "cornerRadius", n => { CornerRadius = n.GetDoubleValue(); } },
                { "cornerSmoothing", n => { CornerSmoothing = n.GetDoubleValue(); } },
                { "effects", n => { Effects = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Effect>(global::Soenneker.Figma.OpenApiClient.Models.Effect.CreateFromDiscriminatorValue)?.AsList(); } },
                { "explicitVariableModes", n => { ExplicitVariableModes = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeExplicitVariableModes>(global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeExplicitVariableModes.CreateFromDiscriminatorValue); } },
                { "exportSettings", n => { ExportSettings = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>(global::Soenneker.Figma.OpenApiClient.Models.ExportSetting.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fills", n => { Fills = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>(global::Soenneker.Figma.OpenApiClient.Models.Paint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gridChildHorizontalAlign", n => { GridChildHorizontalAlign = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildHorizontalAlign>(); } },
                { "gridChildVerticalAlign", n => { GridChildVerticalAlign = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildVerticalAlign>(); } },
                { "gridColumnAnchorIndex", n => { GridColumnAnchorIndex = n.GetDoubleValue(); } },
                { "gridColumnCount", n => { GridColumnCount = n.GetDoubleValue(); } },
                { "gridColumnGap", n => { GridColumnGap = n.GetDoubleValue(); } },
                { "gridColumnSpan", n => { GridColumnSpan = n.GetDoubleValue(); } },
                { "gridColumnsSizing", n => { GridColumnsSizing = n.GetStringValue(); } },
                { "gridRowAnchorIndex", n => { GridRowAnchorIndex = n.GetDoubleValue(); } },
                { "gridRowCount", n => { GridRowCount = n.GetDoubleValue(); } },
                { "gridRowGap", n => { GridRowGap = n.GetDoubleValue(); } },
                { "gridRowSpan", n => { GridRowSpan = n.GetDoubleValue(); } },
                { "gridRowsSizing", n => { GridRowsSizing = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isFixed", n => { IsFixed = n.GetBoolValue(); } },
                { "isMask", n => { IsMask = n.GetBoolValue(); } },
                { "isMaskOutline", n => { IsMaskOutline = n.GetBoolValue(); } },
                { "layoutAlign", n => { LayoutAlign = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutAlign>(); } },
                { "layoutGrow", n => { LayoutGrow = n.GetDoubleValue(); } },
                { "layoutPositioning", n => { LayoutPositioning = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutPositioning>(); } },
                { "layoutSizingHorizontal", n => { LayoutSizingHorizontal = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingHorizontal>(); } },
                { "layoutSizingVertical", n => { LayoutSizingVertical = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingVertical>(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "maskType", n => { MaskType = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasMaskTraitMaskType>(); } },
                { "maxHeight", n => { MaxHeight = n.GetDoubleValue(); } },
                { "maxWidth", n => { MaxWidth = n.GetDoubleValue(); } },
                { "minHeight", n => { MinHeight = n.GetDoubleValue(); } },
                { "minWidth", n => { MinWidth = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "opacity", n => { Opacity = n.GetDoubleValue(); } },
                { "preserveRatio", n => { PreserveRatio = n.GetBoolValue(); } },
                { "rectangleCornerRadii", n => { RectangleCornerRadii = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "relativeTransform", n => { RelativeTransform = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "rotation", n => { Rotation = n.GetDoubleValue(); } },
                { "scrollBehavior", n => { ScrollBehavior = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior>(); } },
                { "shapeType", n => { ShapeType = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeType>(); } },
                { "size", n => { Size = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Vector>(global::Soenneker.Figma.OpenApiClient.Models.Vector.CreateFromDiscriminatorValue); } },
                { "strokeAlign", n => { StrokeAlign = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeAlign>(); } },
                { "strokeDashes", n => { StrokeDashes = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "strokeJoin", n => { StrokeJoin = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeJoin>(); } },
                { "strokeWeight", n => { StrokeWeight = n.GetDoubleValue(); } },
                { "strokes", n => { Strokes = n.GetCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>(global::Soenneker.Figma.OpenApiClient.Models.Paint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "styles", n => { Styles = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeStyles>(global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeStyles.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextType>(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rectangle>("absoluteBoundingBox", AbsoluteBoundingBox);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Rectangle>("absoluteRenderBounds", AbsoluteRenderBounds);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.BlendMode>("blendMode", BlendMode);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitBoundVariables>("boundVariables", BoundVariables);
            writer.WriteStringValue("characters", Characters);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeComponentPropertyReferences>("componentPropertyReferences", ComponentPropertyReferences);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.LayoutConstraint>("constraints", Constraints);
            writer.WriteDoubleValue("cornerRadius", CornerRadius);
            writer.WriteDoubleValue("cornerSmoothing", CornerSmoothing);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Effect>("effects", Effects);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeExplicitVariableModes>("explicitVariableModes", ExplicitVariableModes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.ExportSetting>("exportSettings", ExportSettings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>("fills", Fills);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildHorizontalAlign>("gridChildHorizontalAlign", GridChildHorizontalAlign);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitGridChildVerticalAlign>("gridChildVerticalAlign", GridChildVerticalAlign);
            writer.WriteDoubleValue("gridColumnAnchorIndex", GridColumnAnchorIndex);
            writer.WriteDoubleValue("gridColumnCount", GridColumnCount);
            writer.WriteDoubleValue("gridColumnGap", GridColumnGap);
            writer.WriteDoubleValue("gridColumnSpan", GridColumnSpan);
            writer.WriteStringValue("gridColumnsSizing", GridColumnsSizing);
            writer.WriteDoubleValue("gridRowAnchorIndex", GridRowAnchorIndex);
            writer.WriteDoubleValue("gridRowCount", GridRowCount);
            writer.WriteDoubleValue("gridRowGap", GridRowGap);
            writer.WriteDoubleValue("gridRowSpan", GridRowSpan);
            writer.WriteStringValue("gridRowsSizing", GridRowsSizing);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isFixed", IsFixed);
            writer.WriteBoolValue("isMask", IsMask);
            writer.WriteBoolValue("isMaskOutline", IsMaskOutline);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutAlign>("layoutAlign", LayoutAlign);
            writer.WriteDoubleValue("layoutGrow", LayoutGrow);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutPositioning>("layoutPositioning", LayoutPositioning);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingHorizontal>("layoutSizingHorizontal", LayoutSizingHorizontal);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasLayoutTraitLayoutSizingVertical>("layoutSizingVertical", LayoutSizingVertical);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasMaskTraitMaskType>("maskType", MaskType);
            writer.WriteDoubleValue("maxHeight", MaxHeight);
            writer.WriteDoubleValue("maxWidth", MaxWidth);
            writer.WriteDoubleValue("minHeight", MinHeight);
            writer.WriteDoubleValue("minWidth", MinWidth);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("opacity", Opacity);
            writer.WriteBoolValue("preserveRatio", PreserveRatio);
            writer.WriteCollectionOfPrimitiveValues<double?>("rectangleCornerRadii", RectangleCornerRadii);
            writer.WriteObjectValue<UntypedNode>("relativeTransform", RelativeTransform);
            writer.WriteDoubleValue("rotation", Rotation);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.IsLayerTraitScrollBehavior>("scrollBehavior", ScrollBehavior);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeType>("shapeType", ShapeType);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.Vector>("size", Size);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeAlign>("strokeAlign", StrokeAlign);
            writer.WriteCollectionOfPrimitiveValues<double?>("strokeDashes", StrokeDashes);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.HasGeometryTraitStrokeJoin>("strokeJoin", StrokeJoin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Figma.OpenApiClient.Models.Paint>("strokes", Strokes);
            writer.WriteDoubleValue("strokeWeight", StrokeWeight);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNodeStyles>("styles", Styles);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextType>("type", Type);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
