// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ComponentNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.EllipseNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.EmbedNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.GroupNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.InstanceNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.LineNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.RectangleNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.SectionNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.SliceNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.StarNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.StickyNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.TableCellNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.TableNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.TextNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.TextPathNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.VectorNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode"/>, <see cref="global::Soenneker.Figma.OpenApiClient.Models.WidgetNode"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubcanvasNode : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode? BooleanOperationNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode BooleanOperationNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ComponentNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ComponentNode? ComponentNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ComponentNode ComponentNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode? ComponentSetNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode ComponentSetNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode? ConnectorNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode ConnectorNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.EllipseNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.EllipseNode? EllipseNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.EllipseNode EllipseNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.EmbedNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.EmbedNode? EmbedNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.EmbedNode EmbedNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.FrameNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.FrameNode? FrameNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.FrameNode FrameNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.GroupNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.GroupNode? GroupNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.GroupNode GroupNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.InstanceNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.InstanceNode? InstanceNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.InstanceNode InstanceNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.LineNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.LineNode? LineNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.LineNode LineNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode? LinkUnfurlNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode LinkUnfurlNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.RectangleNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.RectangleNode? RectangleNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.RectangleNode RectangleNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode? RegularPolygonNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode RegularPolygonNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.SectionNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.SectionNode? SectionNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.SectionNode SectionNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode? ShapeWithTextNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode ShapeWithTextNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.SliceNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.SliceNode? SliceNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.SliceNode SliceNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.StarNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.StarNode? StarNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.StarNode StarNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.StickyNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.StickyNode? StickyNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.StickyNode StickyNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.TableCellNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.TableCellNode? TableCellNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.TableCellNode TableCellNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.TableNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.TableNode? TableNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.TableNode TableNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.TextNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.TextNode? TextNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.TextNode TextNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.TextPathNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.TextPathNode? TextPathNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.TextPathNode TextPathNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode? TransformGroupNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode TransformGroupNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.VectorNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.VectorNode? VectorNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.VectorNode VectorNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode? WashiTapeNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode WashiTapeNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Figma.OpenApiClient.Models.WidgetNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.WidgetNode? WidgetNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.WidgetNode WidgetNode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Figma.OpenApiClient.Models.SubcanvasNode();
            if("BooleanOperationNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BooleanOperationNode = new global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode();
            }
            else if("COMPONENT".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentNode = new global::Soenneker.Figma.OpenApiClient.Models.ComponentNode();
            }
            else if("ComponentSetNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentSetNode = new global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode();
            }
            else if("CONNECTOR".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ConnectorNode = new global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode();
            }
            else if("ELLIPSE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EllipseNode = new global::Soenneker.Figma.OpenApiClient.Models.EllipseNode();
            }
            else if("EMBED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EmbedNode = new global::Soenneker.Figma.OpenApiClient.Models.EmbedNode();
            }
            else if("FRAME".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FrameNode = new global::Soenneker.Figma.OpenApiClient.Models.FrameNode();
            }
            else if("GROUP".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GroupNode = new global::Soenneker.Figma.OpenApiClient.Models.GroupNode();
            }
            else if("INSTANCE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InstanceNode = new global::Soenneker.Figma.OpenApiClient.Models.InstanceNode();
            }
            else if("LINE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LineNode = new global::Soenneker.Figma.OpenApiClient.Models.LineNode();
            }
            else if("LinkUnfurlNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LinkUnfurlNode = new global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode();
            }
            else if("RECTANGLE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RectangleNode = new global::Soenneker.Figma.OpenApiClient.Models.RectangleNode();
            }
            else if("RegularPolygonNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RegularPolygonNode = new global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode();
            }
            else if("SECTION".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SectionNode = new global::Soenneker.Figma.OpenApiClient.Models.SectionNode();
            }
            else if("ShapeWithTextNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ShapeWithTextNode = new global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode();
            }
            else if("SLICE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SliceNode = new global::Soenneker.Figma.OpenApiClient.Models.SliceNode();
            }
            else if("STAR".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.StarNode = new global::Soenneker.Figma.OpenApiClient.Models.StarNode();
            }
            else if("STICKY".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.StickyNode = new global::Soenneker.Figma.OpenApiClient.Models.StickyNode();
            }
            else if("TableCellNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TableCellNode = new global::Soenneker.Figma.OpenApiClient.Models.TableCellNode();
            }
            else if("TABLE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TableNode = new global::Soenneker.Figma.OpenApiClient.Models.TableNode();
            }
            else if("TEXT".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TextNode = new global::Soenneker.Figma.OpenApiClient.Models.TextNode();
            }
            else if("TextPathNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TextPathNode = new global::Soenneker.Figma.OpenApiClient.Models.TextPathNode();
            }
            else if("TransformGroupNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TransformGroupNode = new global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode();
            }
            else if("VECTOR".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.VectorNode = new global::Soenneker.Figma.OpenApiClient.Models.VectorNode();
            }
            else if("WashiTapeNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WashiTapeNode = new global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode();
            }
            else if("WIDGET".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WidgetNode = new global::Soenneker.Figma.OpenApiClient.Models.WidgetNode();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BooleanOperationNode != null)
            {
                return BooleanOperationNode.GetFieldDeserializers();
            }
            else if(ComponentNode != null)
            {
                return ComponentNode.GetFieldDeserializers();
            }
            else if(ComponentSetNode != null)
            {
                return ComponentSetNode.GetFieldDeserializers();
            }
            else if(ConnectorNode != null)
            {
                return ConnectorNode.GetFieldDeserializers();
            }
            else if(EllipseNode != null)
            {
                return EllipseNode.GetFieldDeserializers();
            }
            else if(EmbedNode != null)
            {
                return EmbedNode.GetFieldDeserializers();
            }
            else if(FrameNode != null)
            {
                return FrameNode.GetFieldDeserializers();
            }
            else if(GroupNode != null)
            {
                return GroupNode.GetFieldDeserializers();
            }
            else if(InstanceNode != null)
            {
                return InstanceNode.GetFieldDeserializers();
            }
            else if(LineNode != null)
            {
                return LineNode.GetFieldDeserializers();
            }
            else if(LinkUnfurlNode != null)
            {
                return LinkUnfurlNode.GetFieldDeserializers();
            }
            else if(RectangleNode != null)
            {
                return RectangleNode.GetFieldDeserializers();
            }
            else if(RegularPolygonNode != null)
            {
                return RegularPolygonNode.GetFieldDeserializers();
            }
            else if(SectionNode != null)
            {
                return SectionNode.GetFieldDeserializers();
            }
            else if(ShapeWithTextNode != null)
            {
                return ShapeWithTextNode.GetFieldDeserializers();
            }
            else if(SliceNode != null)
            {
                return SliceNode.GetFieldDeserializers();
            }
            else if(StarNode != null)
            {
                return StarNode.GetFieldDeserializers();
            }
            else if(StickyNode != null)
            {
                return StickyNode.GetFieldDeserializers();
            }
            else if(TableCellNode != null)
            {
                return TableCellNode.GetFieldDeserializers();
            }
            else if(TableNode != null)
            {
                return TableNode.GetFieldDeserializers();
            }
            else if(TextNode != null)
            {
                return TextNode.GetFieldDeserializers();
            }
            else if(TextPathNode != null)
            {
                return TextPathNode.GetFieldDeserializers();
            }
            else if(TransformGroupNode != null)
            {
                return TransformGroupNode.GetFieldDeserializers();
            }
            else if(VectorNode != null)
            {
                return VectorNode.GetFieldDeserializers();
            }
            else if(WashiTapeNode != null)
            {
                return WashiTapeNode.GetFieldDeserializers();
            }
            else if(WidgetNode != null)
            {
                return WidgetNode.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BooleanOperationNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.BooleanOperationNode>(null, BooleanOperationNode);
            }
            else if(ComponentNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ComponentNode>(null, ComponentNode);
            }
            else if(ComponentSetNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ComponentSetNode>(null, ComponentSetNode);
            }
            else if(ConnectorNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ConnectorNode>(null, ConnectorNode);
            }
            else if(EllipseNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.EllipseNode>(null, EllipseNode);
            }
            else if(EmbedNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.EmbedNode>(null, EmbedNode);
            }
            else if(FrameNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.FrameNode>(null, FrameNode);
            }
            else if(GroupNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.GroupNode>(null, GroupNode);
            }
            else if(InstanceNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.InstanceNode>(null, InstanceNode);
            }
            else if(LineNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.LineNode>(null, LineNode);
            }
            else if(LinkUnfurlNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.LinkUnfurlNode>(null, LinkUnfurlNode);
            }
            else if(RectangleNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.RectangleNode>(null, RectangleNode);
            }
            else if(RegularPolygonNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.RegularPolygonNode>(null, RegularPolygonNode);
            }
            else if(SectionNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.SectionNode>(null, SectionNode);
            }
            else if(ShapeWithTextNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.ShapeWithTextNode>(null, ShapeWithTextNode);
            }
            else if(SliceNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.SliceNode>(null, SliceNode);
            }
            else if(StarNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.StarNode>(null, StarNode);
            }
            else if(StickyNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.StickyNode>(null, StickyNode);
            }
            else if(TableCellNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.TableCellNode>(null, TableCellNode);
            }
            else if(TableNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.TableNode>(null, TableNode);
            }
            else if(TextNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.TextNode>(null, TextNode);
            }
            else if(TextPathNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.TextPathNode>(null, TextPathNode);
            }
            else if(TransformGroupNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.TransformGroupNode>(null, TransformGroupNode);
            }
            else if(VectorNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.VectorNode>(null, VectorNode);
            }
            else if(WashiTapeNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.WashiTapeNode>(null, WashiTapeNode);
            }
            else if(WidgetNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.WidgetNode>(null, WidgetNode);
            }
        }
    }
}
#pragma warning restore CS0618
