// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>The string literal &apos;TEXTURE&apos; representing the effect&apos;s type. Always check the type before reading other properties.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TextureType
    {
        [EnumMember(Value = "TEXTURE")]
        #pragma warning disable CS1591
        Texture,
        #pragma warning restore CS1591
    }
}
