// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// The `&quot;ON_HOVER&quot;` and `&quot;ON_PRESS&quot;` trigger types revert the navigation when the trigger is finished (the result is temporary). `&quot;MOUSE_ENTER&quot;`, `&quot;MOUSE_LEAVE&quot;`, `&quot;MOUSE_UP&quot;` and `&quot;MOUSE_DOWN&quot;` are permanent, one-way navigation.The `delay` parameter requires the trigger to be held for a certain duration of time before the action occurs.Both `timeout` and `delay` values are in milliseconds.The `&quot;ON_MEDIA_HIT&quot;` and `&quot;ON_MEDIA_END&quot;` trigger types can only trigger from a video. They fire when a video reaches a certain time or ends. The `timestamp` value is in seconds.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Trigger : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The delay property</summary>
        public double? Delay { get; set; }
        /// <summary>Whether this is a [deprecated version](https://help.figma.com/hc/en-us/articles/360040035834-Prototype-triggers#h_01HHN04REHJNP168R26P1CMP0A) of the trigger that was left unchanged for backwards compatibility.If not present, the trigger is the latest version.</summary>
        public bool? DeprecatedVersion { get; set; }
        /// <summary>The device property</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.OnKeyDownTriggerDevice? Device { get; set; }
        /// <summary>The keyCodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? KeyCodes { get; set; }
#nullable restore
#else
        public List<double?> KeyCodes { get; set; }
#endif
        /// <summary>The mediaHitTime property</summary>
        public double? MediaHitTime { get; set; }
        /// <summary>The timeout property</summary>
        public double? Timeout { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.TriggerOneOf1Type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.Trigger"/> and sets the default values.
        /// </summary>
        public Trigger()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.Trigger"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.Trigger CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.Trigger();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "delay", n => { Delay = n.GetDoubleValue(); } },
                { "deprecatedVersion", n => { DeprecatedVersion = n.GetBoolValue(); } },
                { "device", n => { Device = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.OnKeyDownTriggerDevice>(); } },
                { "keyCodes", n => { KeyCodes = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "mediaHitTime", n => { MediaHitTime = n.GetDoubleValue(); } },
                { "timeout", n => { Timeout = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.TriggerOneOf1Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("delay", Delay);
            writer.WriteBoolValue("deprecatedVersion", DeprecatedVersion);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.OnKeyDownTriggerDevice>("device", Device);
            writer.WriteCollectionOfPrimitiveValues<double?>("keyCodes", KeyCodes);
            writer.WriteDoubleValue("mediaHitTime", MediaHitTime);
            writer.WriteDoubleValue("timeout", Timeout);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.TriggerOneOf1Type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
