// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TypePropertiesTraitLineTypesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDERED")]
        #pragma warning disable CS1591
        Ordered,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNORDERED")]
        #pragma warning disable CS1591
        Unordered,
        #pragma warning restore CS1591
    }
}
