// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// An action that affects a video node in the Figma viewer. For example, to play, pause, or skip.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateMediaRuntimeAction : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amountToSkip property</summary>
        public double? AmountToSkip { get; set; }
        /// <summary>The destinationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationId { get; set; }
#nullable restore
#else
        public string DestinationId { get; set; }
#endif
        /// <summary>The mediaAction property</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeActionOneOf1MediaAction? MediaAction { get; set; }
        /// <summary>The newTimestamp property</summary>
        public double? NewTimestamp { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeAction"/> and sets the default values.
        /// </summary>
        public UpdateMediaRuntimeAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amountToSkip", n => { AmountToSkip = n.GetDoubleValue(); } },
                { "destinationId", n => { DestinationId = n.GetStringValue(); } },
                { "mediaAction", n => { MediaAction = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeActionOneOf1MediaAction>(); } },
                { "newTimestamp", n => { NewTimestamp = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amountToSkip", AmountToSkip);
            writer.WriteStringValue("destinationId", DestinationId);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeActionOneOf1MediaAction>("mediaAction", MediaAction);
            writer.WriteDoubleValue("newTimestamp", NewTimestamp);
            writer.WriteEnumValue<global::Soenneker.Figma.OpenApiClient.Models.UpdateMediaRuntimeType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
