// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>Defines the types of data a VariableData object can eventually equal</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VariableResolvedDataType
    {
        [EnumMember(Value = "BOOLEAN")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLOAT")]
        #pragma warning disable CS1591
        FloatValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRING")]
        #pragma warning disable CS1591
        StringValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLOR")]
        #pragma warning disable CS1591
        Color,
        #pragma warning restore CS1591
    }
}
