// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Figma.OpenApiClient.Models
{
    /// <summary>
    /// A color with an independently authored opacity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VariableComposedColor : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColorOneOf1Color? Color { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColorOneOf1Color Color { get; set; }
#endif
        /// <summary>Contains a variable alias</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Figma.OpenApiClient.Models.VariableAlias? Opacity { get; set; }
#nullable restore
#else
        public global::Soenneker.Figma.OpenApiClient.Models.VariableAlias Opacity { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColor"/> and sets the default values.
        /// </summary>
        public VariableComposedColor()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColorOneOf1Color>(global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColorOneOf1Color.CreateFromDiscriminatorValue); } },
                { "opacity", n => { Opacity = n.GetObjectValue<global::Soenneker.Figma.OpenApiClient.Models.VariableAlias>(global::Soenneker.Figma.OpenApiClient.Models.VariableAlias.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.VariableComposedColorOneOf1Color>("color", Color);
            writer.WriteObjectValue<global::Soenneker.Figma.OpenApiClient.Models.VariableAlias>("opacity", Opacity);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
